### ISSUE TITLE
Ansible needs to be upgraded to 2.3.x

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2-tools#31] opened 2017-03-24 01:29 UTC
Required to support with_ in roles. See https://github.com/samsung-cnct/k2/issues/275#issuecomment-288908174

**Comment by davidewatson** [comment] 2017-03-24 15:55
Note that 2.3.0 is not out yet. https://github.com/ansible/ansible/releases

**Comment by davidewatson** [comment] 2017-03-24 16:00
Release should be made by mid-April according to the [roadmap](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_3.rst).

**Comment by DStorck** [comment] 2017-05-15 16:40
dupe of https://github.com/samsung-cnct/k2-tools/issues/42 
closed with https://github.com/samsung-cnct/k2-tools/pull/43

**Closed by DStorck** 2017-05-15 16:40 UTC
Labels: feature request, k2-tools, priority-p2
